### ISSUE TITLE
Auto-update content

### ISSUE THREAD

**Issue by firepick1** [sc-voice/sc-voice#43]
#### User story

When I use Voice, the content will always match the latest content on SuttaCentral

#### Feature description (the list of things that need to be done for the ticket to be considered finished):

- [ ]  Investigate AWS Lambda compute service

#### Pre milestone planning check:
- [ ] Small enough to completed in a milestone.
- [ ] Dependencies marked
- [ ] No external dependencies block this from being completed.
- [ ] Details are understood by dev team so they know what needs to be done and can determine if it can be completed.

**Comment by firepick1** [comment]
AWS Admins can update content. This is good enough.
