### ISSUE TITLE
Developers have access to all AWS Console functions for voice.suttacentral.net

### ISSUE THREAD

**Issue by sabbamitta** [sc-voice/sc-voice#45]
#### User story

SC-Voice should become independent of its originator.

#### Feature description (the list of things that need to be done for the ticket to be considered finished):

- [ ] Developers other than the originator should be able to work on all functions in the AWS console for voice.suttacentral.net.

#### Pre milestone planning check:
- [ ] Small enough to completed in a release.
- [ ] Dependencies marked
- [ ] No external dependencies block this from being completed.
- [ ] Details are understood by dev team so they know what needs to be done and can determine if it can be completed.

**Comment by firepick1** [comment]
SInce Aminah can do everything on her account, we have succeeded!
