### ISSUE TITLE
Improve time indicator

### ISSUE THREAD

**Issue by sabbamitta** [sc-voice/sc-voice#57]
#### User story

The time indicator for sutta reading can be very imprecise, up to a difference of over 20 min to the real reading time. ([More info](https://discourse.suttacentral.net/t/scv-development-v1-3/12312/270))

#### Feature description (the list of things that need to be done for the ticket to be considered finished):

- [ ] Not counting untranslated segments
- [ ] Writing a script for a more specific estimate

#### Pre release planning check:
- [ ] Small enough to completed in a release.
- [ ] Dependencies marked
- [ ] No external dependencies block this from being completed.
- [ ] Details are understood by dev team so they know what needs to be done and can determine if it can be completed.

**Comment by firepick1** [comment]
I think that I'll base the estimate on segment length rather than the actual sound file. The number of text characters should be more information than just counting segments.

**Comment by firepick1** [comment]
Fixed in v1.4.3.
Reassigned to Aminah (I think Aminah entered original request?) for verifying on staging server when it becomes available.

**Comment by firepick1** [comment]
Doesn't work in search results. Only shows up when playing a sutta.

**Comment by firepick1** [comment]
it turns out that i do not have the information available in search results for better time estimates. i have restored the former segment-counting algorithm for search results. The newer algorithm that counts characters is only used when viewing a single sutta then clicking play. 

In this manner, one will see two (2) conflicting time estimates for SN42.11:

* When searching for "root of suffering", SN42.11 shows as 16m 1s (counting segments)
* When viewing SN42.11 and then playing, the time shows as 10m 53s (counting characters)

After looking into this, I think that improving the search time estimates would take some work. I would say 8 story points. Yes, that's almost 3 days. It's that long because I would have to rewrite some deep level stuff to reveal the character counts segment by segment for the search result sutta player. Currently the sutta-player for search results does not know how many characters are remaining because it only works with what it has at any given time, not the entire sutta.

**Comment by Aminah-SC** [comment]
Thanks so much for the work you've done on this. I can really see it's a much more complicated matter than I thought the suggested tweaks would be. 

In terms of review, here're the results of repeat tests of the original tests that led to this ticket (with a couple of extra random ones thrown in):

|Sutta* | v1.3 estimation | staging est. | actual|
|---|---|---|---|
|SN56.11|17m 11s|16m 35s|19m43s|
|SN22.59|16m 53s|9m 28s|12m30s|
|SN35.235|16m 18s|13m 10s|16m10s|
|DN9**|49m 5s|37m 57s|30m02s|
|SN42.11^|n/a| 5m 43s | 3m55s|
|MN67^^|n/a||37m 34s|18m52s|

\* Raveena & Aditi reading 
\** Raveena only
\^ Russell only
\^^ Amy & Aditi

I think this suggests that the gains in accuracy do not outweigh losses in consistency (for which I have not tested, and am just relying on your report above). As such I would recommend this goes back to the backlog and am turning it over to Ang. Sabbamitta.

**Comment by firepick1** [comment]
i have no better algortithm. Removing time estimate and release commitment.

**Comment by sabbamitta** [comment]
Implement time measurement instead of estimate:

"With completion of VSM work, all audio files will be available and present. This allows for an exact time measurement. The current difficulty we have is that we are estimating, not measuring."
See [here](https://discourse.suttacentral.net/t/voice-development-cycle-v1-4/12497/155?u=sabbamitta)

**Comment by firepick1** [comment]
Sutta results now have play times for cached Amy. Times should be accurate to under 12 seconds for cached Amy. To test this, download the sutta to fill the cache, then click on the play button in the search results.  Raveena's times will be slightly shorter.

**Comment by sabbamitta** [comment]
Testing SN12.51:
* Estimate: 11m 29s
* Measurement: 11m 43.06s
SN51.13
* Estimate: 4m 34s
* Measurement: 4m 16.62s
AN4.276
* Estimate: 0m 43s
* Measurement: 0m 47.98s
All tests have been done with Amy, cache filled, and bell sound turned off. More may follow before the release. (No DN suttas though, I am afraid... )

This is not bad so far! :clap:

**Comment by sabbamitta** [comment]
All issues successfully addressed in v1.6. Closing.
