### ISSUE TITLE
Adding segmented Vinaya to SCV (as available)

### ISSUE THREAD

**Issue by sabbamitta** [sc-voice/sc-voice#75]
#### User story

The SC main site includes both suttas and Vinaya in segmented form, and on Voice currently only suttas can be used.

#### Feature description (the list of things that need to be done for the ticket to be considered finished):

- [ ] Add Vinaya to content on Voice.

#### Pre release planning check:
- [ ] Small enough to completed in a release.
- [ ] Dependencies marked
- [ ] No external dependencies block this from being completed.
- [ ] Details are understood by dev team so they know what needs to be done and can determine if it can be completed.

**Comment by sabbamitta** [comment]
This issue is currently blocked by an external dependency: Vinaya content has not yet been fully added to the SC main page, and the parts that are already there have some bugs that need to be addressed by the SC team.

**Comment by sabbamitta** [comment]
Merged with #101.
