### ISSUE TITLE
AI voices for non-english languages

### ISSUE THREAD

**Issue by firepick1** [sc-voice/sc-voice#87]
The priority of Voice support for non-english languages is prioritized according to ease of work:

- [ ] German (Anagarika Sabbamitta, Sophie, Karl) 
- [ ] Spanish (?, Karl)
- [ ] Other AWS Polly languages
- [ ] Sanskrit (Bhante Sujato suggestion)
- [ ] Other Indic languages (Bhante Sujato suggestion)
- [ ] Chinese (last due to insufficient Unicode support and uncertain pronunciation of archaic characters)

**Comment by firepick1** [comment]
We have successfully added German voices. Future issues will be added for each new language.
