### ISSUE TITLE
Improve Accessibility for Vestibular Disorders

### ISSUE THREAD

**Issue by Aminah-SC** [sc-voice/sc-voice#90]
This article focusing on [accessibility issues in connection to vestibular disorders](https://alistapart.com/article/accessibility-for-vestibular) highlights several general accessibility improvements that can be made. 

#### Tasks
- [ ] Review the items point by point
- [ ] Implement relevant small changes
- [ ] Create ticket/s for any larger changes, if applicable.

**Comment by sabbamitta** [comment]
Won't be addressed in the foreseeable future.
